### PR TITLE
Mathis dev

### PR DESCRIPTION
**Pull request by mathisve**
**PLEASE UPDATE YOUR LOGGING CODE TO THE FOLLOWING:**

from now on, if you want to log something do this:

```python
from modules.log import logging

class example(object):
    def __init__(self):
        self.logging = logging()

        try:
            a = "this wont work" / 10
        except Exception as e:
            self.logging.log_error(e) 
```

That will do 3 things:

- print it into the console
- log it to the database
   if this fails, it will log the database exception locally too
- log it locally to `errorlog.txt`

**NOTES:**
I had to add a `create_connection` function to `log.py` because otherwise i'd be importing `database.py` from `log.py` but `database.py` imports `log.py` so it just ends up looping and fails. If you know how to circumvent this in another more elegant way. please let me know.

### CODE REVIEW

**Review by Travis-Owens — APPROVED** [review]
Overall, nice and clean implementation. 

**main.py**
I do have some concerns/questions about how to properly implement the logging object into the threads in a thread-safe manner. However, we'll cross that bridge at a later date.

**log.py**
This is a todo issue, we should consider a database error to be significant and trigger the notification object. Sending an email/SMS to the admin contact.

I don't recall encountering an import loop previously, and will need to do some testing before I can provide feedback on how I think that should work. For now having a create_connection function in the log file will be fine.

**Comment by Travis-Owens** [comment]
Additionally, at a later date we may want to add some configuration variables to the config.py file to control the behavior of the logging function.

**Comment by Travis-Owens** [comment]
#8

**Comment by mathisve** [comment]
Agreed, for now I set `create_connection` to make a new connection for every log rather than running the risk of 2 log exceptions using the same connection at the same time as I have no idea how that would turn out. Also we could maybe have separate database connection for each thread and pass that trough to `log_error`. Idk just spitballing some ideas here.

**Pull request merged**
